In [9]:
import numpy as np
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [10]:
# 1      Generate an array of zeroes using inbuilt numpy function.       
np.ones((3,3)) + np.arange(1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros(3) 

array([0., 0., 0.])

In [12]:
#2  Run the given code and find the dot product of both arrays.

import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[6 8 7 7]
 [9 9 3 9]
 [7 2 2 6]]
[[3 5 6]
 [5 7 9]
 [8 8 9]
 [2 2 4]]


In [13]:
a.dot(b)

array([[128, 156, 199],
       [114, 150, 198],
       [ 59,  77, 102]])

In [14]:
# 3)Read the csv file provided using pandas and display the first 5 entries

import numpy as pd
import pandas as pd

data = pd.read_csv('dataAssignment.csv')

In [15]:
# 4)Describe the data with all features.

data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [16]:
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  
0              State Park   586.48    0.000284   0.135641  
1              State Park   273.16    0.000129   0.080067  
2              State Park   836.47    0.000399   0.119868  
3              State Park   933.78    0.000444   0.128733  
4              State Park   959.33    0.000469   0.125546  
5              State Park   930.30    0.000461   0.166712  
6              State Park  1508.53    0.000751   0.212196  
7              State Park   524.81    0.000256   0.130420  
8     Interpretive Center    14.71    0.000007   0.016774  
9   State Recreation Area    11.40    0.000005   0.009396  
10             State Park  6492.93    0.003136   0.313756  
11             State Park    63.03    0.000030   0.024016  
12  State Recreation Area    51.23    0.000025   0.022095  
13  State Recreation Area   247.11    0.000120   0.050518  
14             State Park   775.28    0.000378   0.145220  
15             State Park   739.52    0.000357   0.191806  
16     State Natural Area   264.84    0.000127   0.067082  
17  State Recreation Area    21.56    0.000010   0.013294  
18  State Nature Preserve    95.89    0.000048   0.040465  
19  State Nature Preserve    72.30    0.000034   0.033885  
20     State Natural Area   174.39    0.000083   0.087192  
21  State Recreation Area  1236.98    0.000615   0.338800  
22  State Recreation Area   695.04    0.000345   0.086487  
23             State Park   569.07    0.000274   0.180257  
24  State Recreation Area    25.22    0.000013   0.026357

In [17]:
#5. Find the total count of missing values for each feature.



data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [18]:
# 6)Display all the unique values from the 'DESCRIPTION’ column.

data.DESCRIPTION

0                State Park
1                State Park
2                State Park
3                State Park
4                State Park
5                State Park
6                State Park
7                State Park
8       Interpretive Center
9     State Recreation Area
10               State Park
11               State Park
12    State Recreation Area
13    State Recreation Area
14               State Park
15               State Park
16       State Natural Area
17    State Recreation Area
18    State Nature Preserve
19    State Nature Preserve
20       State Natural Area
21    State Recreation Area
22    State Recreation Area
23               State Park
24    State Recreation Area
Name: DESCRIPTION, dtype: object

In [19]:
data.DESCRIPTION.value_counts()

State Park               13
State Recreation Area     7
State Nature Preserve     2
State Natural Area        2
Interpretive Center       1
Name: DESCRIPTION, dtype: int64

In [20]:
# 7) Create a grouped table usin 'DESCRIPTION' 
# as the grouping columns with the means of all the other columns.

CopyDataEscription= data.groupby(['DESCRIPTION']).mean()


In [21]:
CopyDataEscription

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [22]:
CopyDataEscription= data.groupby(['DESCRIPTION']).mean([len])
CopyDataEscription

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [23]:
# 8)Generate a random sample of 10 rows from the data.

data.sample(10)

OBJECTID                             UNIT_NAME            DESCRIPTION  \
8         29   Lewis and Clark Interpretive Center    Interpretive Center   
14        33               Turtle River State Park             State Park   
0         21             Fort Stevenson State Park             State Park   
3         24                Fort Ransom State Park             State Park   
12        35  Butte St. Paul State Recreation Area  State Recreation Area   
6         27             Lake Metigoshe State Park             State Park   
21        43   Pembina Gorge State Recreation Area  State Recreation Area   
1         22                Beaver Lake State Park             State Park   
11        32                Sully Creek State Park             State Park   
9         30     Fort Mandan State Recreation Area  State Recreation Area   

      ACRES  SHAPE.AREA  SHAPE.LEN  
8     14.71    0.000007   0.016774  
14   775.28    0.000378   0.145220  
0    586.48    0.000284   0.135641  
3    933.78    0.000444   0.128733  
12    51.23    0.000025   0.022095  
6   1508.53    0.000751   0.212196  
21  1236.98    0.000615   0.338800  
1    273.16    0.000129   0.080067  
11    63.03    0.000030   0.024016  
9     11.40    0.000005   0.009396

In [24]:
# 9 Add a Feature called 'New_feature' to the new Dataset 
# and Add Random float Values in between 0 and 1 using Numpy.

data["New Feature"] = np.random.rand(25) # np.random.rand(rows ) ...., col)

In [27]:
data["New Feature"]

0     0.758094
1     0.914454
2     0.794731
3     0.998915
4     0.454007
5     0.423028
6     0.594051
7     0.199901
8     0.718085
9     0.055804
10    0.042241
11    0.842358
12    0.668124
13    0.836391
14    0.237600
15    0.797973
16    0.280844
17    0.685731
18    0.626413
19    0.708881
20    0.605289
21    0.215063
22    0.233208
23    0.745757
24    0.759090
Name: New Feature, dtype: float64

In [28]:
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New Feature  
0              State Park   586.48    0.000284   0.135641     0.758094  
1              State Park   273.16    0.000129   0.080067     0.914454  
2              State Park   836.47    0.000399   0.119868     0.794731  
3              State Park   933.78    0.000444   0.128733     0.998915  
4              State Park   959.33    0.000469   0.125546     0.454007  
5              State Park   930.30    0.000461   0.166712     0.423028  
6              State Park  1508.53    0.000751   0.212196     0.594051  
7              State Park   524.81    0.000256   0.130420     0.199901  
8     Interpretive Center    14.71    0.000007   0.016774     0.718085  
9   State Recreation Area    11.40    0.000005   0.009396     0.055804  
10             State Park  6492.93    0.003136   0.313756     0.042241  
11             State Park    63.03    0.000030   0.024016     0.842358  
12  State Recreation Area    51.23    0.000025   0.022095     0.668124  
13  State Recreation Area   247.11    0.000120   0.050518     0.836391  
14             State Park   775.28    0.000378   0.145220     0.237600  
15             State Park   739.52    0.000357   0.191806     0.797973  
16     State Natural Area   264.84    0.000127   0.067082     0.280844  
17  State Recreation Area    21.56    0.000010   0.013294     0.685731  
18  State Nature Preserve    95.89    0.000048   0.040465     0.626413  
19  State Nature Preserve    72.30    0.000034   0.033885     0.708881  
20     State Natural Area   174.39    0.000083   0.087192     0.605289  
21  State Recreation Area  1236.98    0.000615   0.338800     0.215063  
22  State Recreation Area   695.04    0.000345   0.086487     0.233208  
23             State Park   569.07    0.000274   0.180257     0.745757  
24  State Recreation Area    25.22    0.000013   0.026357     0.759090

In [29]:
#10 Replace zero value of column 'OBJECTID' with mean value permanently.

P10 = data.OBJECTID.mean()

In [32]:
data.OBJECTID.replace(0 , P10, inplace= True)

In [33]:
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         33                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New Feature  
0              State Park   586.48    0.000284   0.135641     0.758094  
1              State Park   273.16    0.000129   0.080067     0.914454  
2              State Park   836.47    0.000399   0.119868     0.794731  
3              State Park   933.78    0.000444   0.128733     0.998915  
4              State Park   959.33    0.000469   0.125546     0.454007  
5              State Park   930.30    0.000461   0.166712     0.423028  
6              State Park  1508.53    0.000751   0.212196     0.594051  
7              State Park   524.81    0.000256   0.130420     0.199901  
8     Interpretive Center    14.71    0.000007   0.016774     0.718085  
9   State Recreation Area    11.40    0.000005   0.009396     0.055804  
10             State Park  6492.93    0.003136   0.313756     0.042241  
11             State Park    63.03    0.000030   0.024016     0.842358  
12  State Recreation Area    51.23    0.000025   0.022095     0.668124  
13  State Recreation Area   247.11    0.000120   0.050518     0.836391  
14             State Park   775.28    0.000378   0.145220     0.237600  
15             State Park   739.52    0.000357   0.191806     0.797973  
16     State Natural Area   264.84    0.000127   0.067082     0.280844  
17  State Recreation Area    21.56    0.000010   0.013294     0.685731  
18  State Nature Preserve    95.89    0.000048   0.040465     0.626413  
19  State Nature Preserve    72.30    0.000034   0.033885     0.708881  
20     State Natural Area   174.39    0.000083   0.087192     0.605289  
21  State Recreation Area  1236.98    0.000615   0.338800     0.215063  
22  State Recreation Area   695.04    0.000345   0.086487     0.233208  
23             State Park   569.07    0.000274   0.180257     0.745757  
24  State Recreation Area    25.22    0.000013   0.026357     0.759090